Check generate-documentation if target branch exists

diff --git a/script/generate-documentation b/script/generate-documentation
--- a/script/generate-documentation
+++ b/script/generate-documentation
@@ -64,6 +64,18 @@ anything_changed() {
     test "$other_files_changed" -gt 0 || test "$((lines_changed_in_index+lines_changed_in_api))" -gt 0
 }
 
+check_branch_exists() {
+    local repo=$1
+    local branch=$2
+
+    if git ls-remote --exit-code -- "$repo" "$branch" ; then
+        return
+    fi
+
+    echo "Branch $branch is not found at $repo, exiting"
+    (exit 1)
+}
+
 update_docs() {
         mkdir out || exit 1
         (
@@ -162,6 +174,13 @@ tmpwd=$(mktemp -d -t openqa-doc-XXXX)
 PUSH_REMOTE_URL="${1:-$(git config --get remote.origin.url)}"
 PUSH_BRANCH="${2:-gh-pages}"
 PUBLISH="${PUBLISH}"
+
+# if target branch doesn't exits we just exit
+if [[ -z "${PULL_REQUEST_USER}" ]]; then
+    check_branch_exists "$PUSH_REMOTE_URL" "$PUSH_BRANCH" || exit 0
+else
+    check_branch_exists "https://github.com/$PULL_REQUEST_USER/openQA" "gh-pages" || exit 0
+fi
 
 check_asciidoctor() {
     asciidoctor_bin=$(command -v asciidoctor) || true
